"""Differential equations helpers for lessons and practice."""

from edumath.differential_equations.concepts import (
    DIFFERENTIAL_EQUATIONS_PATH,
    FIRST_ORDER_EQUATIONS,
    LINEAR_EQUATIONS,
    SEPARABLE_EQUATIONS,
    SLOPE_FIELDS,
    SYSTEMS,
)
from edumath.differential_equations.exercises import (
    classify_ode_exercise,
    equilibrium_exercise,
    euler_step_exercise,
    linear_integrating_factor_exercise,
    separable_solution_exercise,
    system_equilibrium_exercise,
)
from edumath.differential_equations.plots import (
    PhaseLine2D,
    SlopeField2D,
    euler_method_scene,
    linear_system_phase_plane_scene,
    phase_line_scene,
    slope_field_scene,
    solution_family_scene,
)
from edumath.differential_equations.quizzes import (
    classify_ode_question,
    differential_equations_diagnostic_quiz,
    equilibrium_question,
    euler_step_question,
    initial_condition_question,
    slope_field_behavior_question,
    solution_verification_question,
)
from edumath.differential_equations.solvers import (
    DerivativeFunction,
    SlopeSample,
    SystemDerivativeFunction,
    SystemState,
    classify_equilibrium_1d,
    direction_field_values,
    equilibrium_points_1d,
    euler_method,
    improved_euler_method,
    system_euler_method,
)
from edumath.differential_equations.validators import (
    ODE_TOLERANCE,
    TRAJECTORY_TOLERANCE,
    validate_equilibrium,
    validate_initial_condition,
    validate_numeric_trajectory,
    validate_solution_satisfies_ode,
)

__all__ = [
    "DIFFERENTIAL_EQUATIONS_PATH",
    "FIRST_ORDER_EQUATIONS",
    "LINEAR_EQUATIONS",
    "ODE_TOLERANCE",
    "SEPARABLE_EQUATIONS",
    "SLOPE_FIELDS",
    "SYSTEMS",
    "TRAJECTORY_TOLERANCE",
    "DerivativeFunction",
    "PhaseLine2D",
    "SlopeField2D",
    "SlopeSample",
    "SystemDerivativeFunction",
    "SystemState",
    "classify_equilibrium_1d",
    "classify_ode_exercise",
    "classify_ode_question",
    "differential_equations_diagnostic_quiz",
    "direction_field_values",
    "equilibrium_exercise",
    "equilibrium_points_1d",
    "equilibrium_question",
    "euler_method",
    "euler_method_scene",
    "euler_step_exercise",
    "euler_step_question",
    "improved_euler_method",
    "initial_condition_question",
    "linear_integrating_factor_exercise",
    "linear_system_phase_plane_scene",
    "phase_line_scene",
    "separable_solution_exercise",
    "slope_field_behavior_question",
    "slope_field_scene",
    "solution_family_scene",
    "solution_verification_question",
    "system_equilibrium_exercise",
    "system_euler_method",
    "validate_equilibrium",
    "validate_initial_condition",
    "validate_numeric_trajectory",
    "validate_solution_satisfies_ode",
]
