{
  "hash": "e14f6d20d7ee72d173c3c746cdd34417",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Estimation\ndescription: Point estimates, confidence intervals, margin of error, and uncertainty.\nexecute:\n  echo: false\n---\n\nEstimation uses sample data to approximate an unknown population quantity. A good\nestimate should include uncertainty, because a different random sample would\nusually give a different result.\n\n::: {.learning-objectives}\n### Learning objectives\n\nAfter this lesson you should be able to:\n\n- distinguish point estimates from interval estimates;\n- compute a margin of error from a critical value and standard error;\n- build introductory confidence intervals for means and proportions;\n- interpret confidence level correctly;\n- explain how sample size, spread, and confidence level affect interval width;\n- use `edumath` to verify confidence interval calculations.\n:::\n\n## Parameters and estimates\n\nA **parameter** is an unknown number about a population, such as a true mean\n`mu` or true proportion `p`.\n\nA **point estimate** is one sample-based guess, such as sample mean `x-bar` or\nsample proportion `p-hat`.\n\nA point estimate is useful but incomplete because it does not show uncertainty.\n\n## Confidence intervals\n\nA confidence interval has the form:\n\n::: {.formula-box}\n```text\nestimate ± margin of error\n```\n:::\n\nFor many introductory normal-approximation settings:\n\n```text\nmargin of error = critical value * standard error\n```\n\nA `95%` normal critical value is approximately `1.96`.\n\n## Interpreting confidence level\n\nA `95%` confidence level means that if we repeatedly used the same method on many\nrandom samples, about `95%` of the intervals would contain the true parameter.\n\nIt does **not** mean there is a `95%` probability that one already-computed\ninterval contains the fixed parameter. In introductory courses we often use\ninformal language, but the more precise idea is long-run performance of the\nmethod.\n\n## What changes interval width?\n\nIntervals become wider when:\n\n- confidence level increases;\n- data are more variable;\n- sample size is smaller.\n\nIntervals become narrower when:\n\n- confidence level decreases;\n- data are less variable;\n- sample size increases.\n\n## Worked example 1: confidence interval for a mean\n\nA sample of `36` observations has mean `50` and standard deviation `12`. Use an\napproximate `95%` interval for the population mean.\n\n**Step 1: Compute standard error.**\n\n```text\nSE = s / sqrt(n) = 12 / sqrt(36) = 12 / 6 = 2\n```\n\n**Step 2: Compute margin of error.**\n\n```text\nME = 1.96 * 2 = 3.92\n```\n\n**Step 3: Build the interval.**\n\n```text\n50 ± 3.92 = (46.08, 53.92)\n```\n\n**Step 4: Interpret.**\n\nWe are `95%` confident, using this method, that the population mean is between\nabout `46.08` and `53.92`, assuming the sampling conditions are appropriate.\n\n## Worked example 2: confidence interval for a proportion\n\nIn a sample of `100` people, `60` say yes. Estimate the population yes\nproportion with a `95%` confidence interval.\n\n**Step 1: Find the sample proportion.**\n\n```text\np-hat = 60 / 100 = 0.60\n```\n\n**Step 2: Find standard error.**\n\n```text\nSE = sqrt(p-hat(1-p-hat)/n)\nSE = sqrt(0.60 * 0.40 / 100)\nSE = sqrt(0.0024)\nSE is about 0.049\n```\n\n**Step 3: Find margin of error.**\n\n```text\nME = 1.96 * 0.049, about 0.096\n```\n\n**Step 4: Build the interval.**\n\n```text\n0.60 ± 0.096 = (0.504, 0.696)\n```\n\n**Interpretation:** The data are consistent with a population yes proportion from\nabout `50.4%` to `69.6%`, under the usual conditions.\n\n## Worked example 3: explain a wider interval\n\nTwo studies estimate the same mean with the same standard deviation. Study A has\n`n=25`; Study B has `n=100`.\n\n**Question:** Which interval is wider?\n\n**Reasoning:**\n\n```text\nSE_A = s / sqrt(25) = s/5\nSE_B = s / sqrt(100) = s/10\n```\n\nStudy A has larger standard error, so its interval is wider.\n\n## Common pitfalls\n\n- Saying \"there is a 95% probability the parameter is in this interval\" without\n  understanding the frequentist meaning.\n- Forgetting that a confidence interval depends on sampling conditions.\n- Reporting an interval without context or units.\n- Thinking a narrow interval is good if the sampling method was biased.\n- Confusing confidence level with the sample proportion.\n\n## Practice exercises\n\n::: {.practice-box}\n1. What is a point estimate?\n2. A mean is `80`, standard error is `4`, and critical value is `1.96`. Find the\n   `95%` interval.\n3. If confidence level increases from `90%` to `99%`, does the interval usually\n   get wider or narrower?\n4. If sample size increases, what usually happens to margin of error?\n5. Interpret the interval `(12.4, 18.8)` for a population mean measured in hours.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions\n\n1. A single-number estimate of a population parameter, such as a sample mean.\n2. Margin of error `=1.96(4)=7.84`; interval `(72.16, 87.84)`.\n3. Wider, because higher confidence requires a larger critical value.\n4. It usually decreases because standard error decreases.\n5. A careful interpretation: using the method and assumptions, we are confident\n   that the population mean is between `12.4` and `18.8` hours.\n:::\n\n## Subtopic guided practice and checkpoints\n\n### Lab 1: estimate versus parameter\n\n**Guess first.** Is `p-hat=0.42` a parameter or statistic?\n\n**Guided exercise.**\n\n`p-hat` is computed from a sample, so it is a statistic and a point estimate of\npopulation proportion `p`.\n\n::: {.practice-box}\n**Checkpoint.** Is population mean `mu` a parameter or statistic?\n:::\n\n### Lab 2: build margin of error\n\n**Guess first.** If standard error doubles, what happens to margin of error?\n\n**Guided exercise.**\n\nSince `ME = critical value * SE`, doubling `SE` doubles the margin of error.\n\n::: {.practice-box}\n**Checkpoint.** Find margin of error when critical value is `2` and `SE=3`.\n:::\n\n### Lab 3: interval interpretation\n\n**Guess first.** Does a confidence interval prove the parameter is inside?\n\n**Guided exercise.**\n\nNo. It gives a plausible range using a method with known long-run performance.\nThe interval can miss the true parameter.\n\n::: {.practice-box}\n**Checkpoint.** What does `95%` confidence describe: the single interval or the\nlong-run method?\n:::\n\n### Lab 4: width decisions\n\n**Guess first.** Which is wider: a `90%` interval or a `99%` interval from the\nsame data?\n\n**Guided exercise.**\n\nThe `99%` interval is wider because it requires more confidence.\n\n::: {.practice-box}\n**Checkpoint.** What happens to interval width if data are more variable?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Lab checkpoint answers\n\n1. Parameter.\n2. `ME=6`.\n3. The long-run method.\n4. It gets wider, all else equal.\n:::\n\n## Estimation guessing game\n\n<script type=\"application/json\" class=\"edu-math-statistics-checkpoint-config\">\n{\n  \"topic\": \"estimation\",\n  \"title\": \"Estimation checkpoint\",\n  \"defaultTotal\": 5\n}\n</script>\n\n<div class=\"quiz-shell edu-math-statistics-checkpoint\" data-default-total=\"4\"></div>\n\n<script>\n  (() => {\n    const DEFAULT_TOPIC = \"descriptive-statistics\";\n    const BANKS = {\n      \"descriptive-statistics\": [meanQuestion, medianQuestion, iqrQuestion, outlierQuestion],\n      sampling: [populationQuestion, biasQuestion, randomSampleQuestion, confoundingQuestion],\n      \"probability-for-statistics\": [expectedValueQuestion, varianceQuestion, normalModelQuestion, binomialQuestion],\n      \"sampling-distributions\": [standardErrorQuestion, cltQuestion, samplingDistributionQuestion, sampleSizeQuestion],\n      estimation: [pointEstimateQuestion, confidenceIntervalQuestion, marginQuestion, confidenceMeaningQuestion],\n      \"hypothesis-tests\": [nullQuestion, pValueQuestion, alphaQuestion, typeErrorQuestion],\n      \"comparing-groups\": [pairedQuestion, independentQuestion, differenceQuestion, effectSizeQuestion],\n      \"chi-square-tests\": [observedExpectedQuestion, goodnessFitQuestion, independenceQuestion, chiSquareCautionQuestion],\n      \"regression-basics\": [slopeQuestion, residualQuestion, correlationQuestion, causationQuestion],\n      \"statistics-cumulative-review\": [meanQuestion, biasQuestion, standardErrorQuestion, confidenceIntervalQuestion, pValueQuestion, slopeQuestion],\n    };\n\n    document.querySelectorAll(\".edu-math-statistics-checkpoint:not([data-ready])\").forEach(init);\n\n    function init(root) {\n      const config = readConfig(root);\n      const state = { config, total: config.defaultTotal, index: 0, score: 0 };\n      root.dataset.ready = \"true\";\n      renderStart(root, state);\n    }\n\n    function readConfig(root) {\n      const node = root.previousElementSibling;\n      let parsed = {};\n      if (node?.classList?.contains(\"edu-math-statistics-checkpoint-config\")) {\n        try {\n          parsed = JSON.parse(node.textContent || \"{}\");\n        } catch {\n          parsed = {};\n        }\n      }\n      return {\n        topic: parsed.topic || root.dataset.topic || DEFAULT_TOPIC,\n        title: parsed.title || \"Statistics checkpoint\",\n        defaultTotal: Math.max(1, Math.min(20, Number(parsed.defaultTotal || 4))),\n      };\n    }\n\n    function renderStart(root, state) {\n      root.replaceChildren();\n      const input = element(\"input\", {\n        class: \"quiz-count\",\n        type: \"number\",\n        min: \"1\",\n        max: \"20\",\n        value: String(state.total),\n      });\n      const button = element(\"button\", { type: \"button\" }, \"Start checkpoint\");\n      button.addEventListener(\"click\", () => {\n        state.total = Math.max(1, Math.min(20, Number(input.value) || 4));\n        state.index = 0;\n        state.score = 0;\n        renderQuestion(root, state, makeQuestion(state.config.topic));\n      });\n      root.append(\n        element(\"p\", { class: \"quiz-topic\" }, state.config.title),\n        element(\"div\", { class: \"quiz-start\" }, element(\"label\", {}, element(\"span\", {}, \"Number of questions\"), input), button),\n      );\n    }\n\n    function renderQuestion(root, state, question) {\n      root.replaceChildren();\n      let answered = false;\n      const progress = element(\n        \"div\",\n        { class: \"quiz-progress\" },\n        element(\"span\", {}, `Question ${state.index + 1} of ${state.total}`),\n        element(\"span\", {}, `Score: ${state.score}/${state.total}`),\n      );\n      const feedback = element(\"p\", { class: \"quiz-feedback\", \"aria-live\": \"polite\" });\n      const next = element(\"button\", { type: \"button\", disabled: \"\" }, \"Next question\");\n      const options = radioList(question.options, (selected) => {\n        if (answered) return;\n        answered = true;\n        const correct = selected === question.answer;\n        if (correct) state.score += 1;\n        feedback.className = correct ? \"quiz-feedback correct\" : \"quiz-feedback wrong\";\n        feedback.replaceChildren(correct ? \"Correct.\" : `Not quite. The answer is ${question.answer}.`, \" \", question.explanation);\n        options.querySelectorAll(\"input\").forEach((input) => {\n          input.disabled = true;\n        });\n        progress.lastElementChild.textContent = `Score: ${state.score}/${state.total}`;\n        next.disabled = false;\n      });\n      next.addEventListener(\"click\", () => {\n        state.index += 1;\n        if (state.index >= state.total) renderDone(root, state);\n        else renderQuestion(root, state, makeQuestion(state.config.topic));\n      });\n      root.append(progress, stimulus(question.stimulus), element(\"p\", { class: \"quiz-prompt\" }, question.prompt), feedback, options, next);\n    }\n\n    function renderDone(root, state) {\n      root.replaceChildren();\n      const restart = element(\"button\", { type: \"button\" }, \"Try again\");\n      restart.addEventListener(\"click\", () => renderStart(root, state));\n      root.append(element(\"h3\", {}, \"Checkpoint complete\"), element(\"p\", {}, `Final score: ${state.score}/${state.total}`), restart);\n    }\n\n    function makeQuestion(topic) {\n      const bank = BANKS[topic] || BANKS[DEFAULT_TOPIC];\n      return choice(bank)();\n    }\n\n    function meanQuestion() {\n      return question({ prompt: \"What is the mean of 2, 4, and 6?\", stimulus: \"add then divide by 3\", answer: \"4\", distractors: [\"3\", \"6\", \"12\"], explanation: \"(2+4+6)/3 = 4.\" });\n    }\n    function medianQuestion() {\n      return question({ prompt: \"Which summary is most resistant to one very large outlier?\", stimulus: \"center with outliers\", answer: \"median\", distractors: [\"mean\", \"range\", \"maximum\"], explanation: \"The median depends on order position, not the exact size of the extreme value.\" });\n    }\n    function iqrQuestion() {\n      return question({ prompt: \"What does the IQR measure?\", stimulus: \"Q3 - Q1\", answer: \"spread of the middle half\", distractors: [\"average value\", \"sample size\", \"largest value only\"], explanation: \"IQR is the distance from the first quartile to the third quartile.\" });\n    }\n    function outlierQuestion() {\n      return question({ prompt: \"A value far above the rest usually affects which summary most?\", stimulus: \"outlier\", answer: \"mean\", distractors: [\"median\", \"Q1\", \"sample size\"], explanation: \"The mean uses the exact size of every value.\" });\n    }\n    function populationQuestion() {\n      return question({ prompt: \"The full group we want to learn about is the...\", stimulus: \"study target\", answer: \"population\", distractors: [\"sample\", \"statistic\", \"response\"], explanation: \"A sample is selected from the population.\" });\n    }\n    function biasQuestion() {\n      return question({ prompt: \"Surveying only gym visitors about exercise is mainly what problem?\", stimulus: \"who was selected\", answer: \"selection bias\", distractors: [\"random sampling\", \"larger sample size\", \"low variance\"], explanation: \"The selected group systematically differs from the target population.\" });\n    }\n    function randomSampleQuestion() {\n      return question({ prompt: \"Why do random samples help?\", stimulus: \"chance selection\", answer: \"they reduce systematic selection patterns\", distractors: [\"they remove all uncertainty\", \"they prove causation\", \"they make every answer true\"], explanation: \"Random selection supports probability-based uncertainty estimates.\" });\n    }\n    function confoundingQuestion() {\n      return question({ prompt: \"A hidden variable related to both treatment and outcome is called a...\", stimulus: \"causal caution\", answer: \"confounder\", distractors: [\"median\", \"residual\", \"margin of error\"], explanation: \"Confounding can create misleading associations.\" });\n    }\n    function expectedValueQuestion() {\n      return question({ prompt: \"Expected value is best described as a...\", stimulus: \"weighted average\", answer: \"long-run average\", distractors: [\"guaranteed outcome\", \"sample maximum\", \"p-value\"], explanation: \"Expected value averages outcomes using probabilities as weights.\" });\n    }\n    function varianceQuestion() {\n      return question({ prompt: \"Variance measures typical squared distance from the...\", stimulus: \"spread\", answer: \"mean\", distractors: [\"maximum\", \"sample size\", \"p-value\"], explanation: \"Variance averages squared deviations from the mean.\" });\n    }\n    function normalModelQuestion() {\n      return question({ prompt: \"The normal distribution is shaped like a...\", stimulus: \"symmetric model\", answer: \"bell\", distractors: [\"line\", \"triangle\", \"two-way table\"], explanation: \"Normal models are symmetric and bell-shaped.\" });\n    }\n    function binomialQuestion() {\n      return question({ prompt: \"A binomial count records the number of...\", stimulus: \"fixed independent trials\", answer: \"successes\", distractors: [\"outliers\", \"residuals\", \"quartiles\"], explanation: \"Binomial variables count successes in a fixed number of independent trials.\" });\n    }\n    function standardErrorQuestion() {\n      return question({ prompt: \"Standard error describes variation of a...\", stimulus: \"sample-to-sample\", answer: \"statistic\", distractors: [\"single raw value\", \"population label\", \"survey question wording\"], explanation: \"It is the standard deviation of a statistic's sampling distribution.\" });\n    }\n    function cltQuestion() {\n      return question({ prompt: \"The central limit theorem says sample means often become approximately...\", stimulus: \"large n\", answer: \"normal\", distractors: [\"categorical\", \"impossible\", \"biased\"], explanation: \"With conditions, the distribution of sample means is approximately normal.\" });\n    }\n    function samplingDistributionQuestion() {\n      return question({ prompt: \"A sampling distribution is the distribution of...\", stimulus: \"repeat sampling\", answer: \"a statistic\", distractors: [\"one questionnaire\", \"a population name\", \"a graph title\"], explanation: \"Imagine calculating the statistic for many random samples.\" });\n    }\n    function sampleSizeQuestion() {\n      return question({ prompt: \"If sample size increases, standard error usually...\", stimulus: \"SE = s/sqrt(n)\", answer: \"decreases\", distractors: [\"increases\", \"stays forced at 1\", \"becomes a p-value\"], explanation: \"The square root of n is in the denominator.\" });\n    }\n    function pointEstimateQuestion() {\n      return question({ prompt: \"A single-number estimate is a...\", stimulus: \"one value\", answer: \"point estimate\", distractors: [\"confidence level\", \"null hypothesis\", \"residual\"], explanation: \"A sample mean or sample proportion can be a point estimate.\" });\n    }\n    function confidenceIntervalQuestion() {\n      return question({ prompt: \"A confidence interval is estimate plus/minus...\", stimulus: \"uncertainty\", answer: \"margin of error\", distractors: [\"sample maximum\", \"correlation\", \"confounder\"], explanation: \"The margin of error measures how far the interval extends from the estimate.\" });\n    }\n    function marginQuestion() {\n      return question({ prompt: \"For a 95% normal interval, the multiplier is about...\", stimulus: \"critical value\", answer: \"1.96\", distractors: [\"0.05\", \"10\", \"100\"], explanation: \"A two-sided 95% normal interval uses z* approximately 1.96.\" });\n    }\n    function confidenceMeaningQuestion() {\n      return question({ prompt: \"95% confidence describes the long-run success rate of the...\", stimulus: \"repeated samples\", answer: \"method\", distractors: [\"single fixed interval\", \"null being true\", \"largest observation\"], explanation: \"The confidence level belongs to the procedure over repeated samples.\" });\n    }\n    function nullQuestion() {\n      return question({ prompt: \"The baseline claim in a test is the...\", stimulus: \"H0\", answer: \"null hypothesis\", distractors: [\"sample statistic\", \"residual\", \"histogram\"], explanation: \"The null often represents no change, no effect, or an existing claim.\" });\n    }\n    function pValueQuestion() {\n      return question({ prompt: \"A p-value is computed assuming which hypothesis is true?\", stimulus: \"test logic\", answer: \"null hypothesis\", distractors: [\"alternative hypothesis\", \"largest value\", \"regression line\"], explanation: \"It measures how surprising the data are under the null model.\" });\n    }\n    function alphaQuestion() {\n      return question({ prompt: \"If p-value <= alpha, the usual decision is to...\", stimulus: \"decision rule\", answer: \"reject the null\", distractors: [\"prove the null\", \"ignore the data\", \"increase sample bias\"], explanation: \"The result is statistically significant at that alpha level.\" });\n    }\n    function typeErrorQuestion() {\n      return question({ prompt: \"Rejecting a true null hypothesis is a Type...\", stimulus: \"false positive\", answer: \"I error\", distractors: [\"II error\", \"residual\", \"quartile\"], explanation: \"Type I error is a false positive decision.\" });\n    }\n    function pairedQuestion() {\n      return question({ prompt: \"Before-and-after measurements on the same people are...\", stimulus: \"same units twice\", answer: \"paired\", distractors: [\"independent\", \"categorical only\", \"a histogram\"], explanation: \"Pairing means observations are naturally linked.\" });\n    }\n    function independentQuestion() {\n      return question({ prompt: \"Two separate randomly selected groups are usually treated as...\", stimulus: \"different units\", answer: \"independent samples\", distractors: [\"paired samples\", \"one residual\", \"one population parameter\"], explanation: \"No observation in one group is matched to a specific observation in the other.\" });\n    }\n    function differenceQuestion() {\n      return question({ prompt: \"When comparing two means, the estimate is often...\", stimulus: \"group A minus group B\", answer: \"a difference\", distractors: [\"a maximum\", \"a p-value only\", \"a sample label\"], explanation: \"The difference in sample means estimates the difference in population means.\" });\n    }\n    function effectSizeQuestion() {\n      return question({ prompt: \"Practical importance is mostly about the...\", stimulus: \"real-world size\", answer: \"effect size\", distractors: [\"file name\", \"random seed\", \"graph color\"], explanation: \"A tiny effect can be statistically significant but not practically important.\" });\n    }\n    function observedExpectedQuestion() {\n      return question({ prompt: \"Chi-square statistics compare observed counts to...\", stimulus: \"null model\", answer: \"expected counts\", distractors: [\"sample means\", \"residual plots\", \"confidence levels\"], explanation: \"Expected counts are what the null model predicts for each category.\" });\n    }\n    function goodnessFitQuestion() {\n      return question({ prompt: \"A goodness-of-fit test uses how many categorical variables?\", stimulus: \"one-way table\", answer: \"one\", distractors: [\"two\", \"three slopes\", \"no counts\"], explanation: \"It compares one categorical distribution to a claimed distribution.\" });\n    }\n    function independenceQuestion() {\n      return question({ prompt: \"A chi-square test of independence uses a...\", stimulus: \"two categorical variables\", answer: \"two-way table\", distractors: [\"scatterplot only\", \"sample mean\", \"slope formula\"], explanation: \"Rows and columns represent the two categorical variables.\" });\n    }\n    function chiSquareCautionQuestion() {\n      return question({ prompt: \"Chi-square methods are based on...\", stimulus: \"categorical data\", answer: \"counts\", distractors: [\"raw angles\", \"regression slopes only\", \"derivatives\"], explanation: \"The data should be frequency counts in categories.\" });\n    }\n    function slopeQuestion() {\n      return question({ prompt: \"In regression, slope is the predicted change in y for...\", stimulus: \"one-unit change\", answer: \"one more unit of x\", distractors: [\"one more residual\", \"the median only\", \"a smaller p-value\"], explanation: \"Slope connects changes in the explanatory variable to predicted changes in the response.\" });\n    }\n    function residualQuestion() {\n      return question({ prompt: \"A residual is observed y minus...\", stimulus: \"prediction error\", answer: \"predicted y\", distractors: [\"mean x\", \"sample size\", \"confidence level\"], explanation: \"Residuals show prediction errors for individual points.\" });\n    }\n    function correlationQuestion() {\n      return question({ prompt: \"Correlation is always between...\", stimulus: \"r\", answer: \"-1 and 1\", distractors: [\"0 and 100\", \"1 and infinity\", \"only positive values\"], explanation: \"Pearson correlation ranges from -1 to 1.\" });\n    }\n    function causationQuestion() {\n      return question({ prompt: \"A strong regression association alone proves causation?\", stimulus: \"causal caution\", answer: \"no\", distractors: [\"yes\", \"always\", \"only if slope is positive\"], explanation: \"Confounding and study design matter for causal claims.\" });\n    }\n\n    function question({ prompt, stimulus, answer, distractors, explanation }) {\n      return { prompt, stimulus, answer, options: shuffle([answer, ...distractors]), explanation };\n    }\n    function radioList(options, onSelect) {\n      const name = `statistics-checkpoint-${Math.random().toString(36).slice(2)}`;\n      const container = element(\"div\", { class: \"quiz-options\" });\n      options.forEach((option) => {\n        const input = element(\"input\", { type: \"radio\", name, value: option });\n        input.addEventListener(\"change\", () => onSelect(option));\n        container.append(element(\"label\", {}, input, element(\"span\", {}, option)));\n      });\n      return container;\n    }\n    function stimulus(text) {\n      return element(\"pre\", { class: \"quiz-stimulus\" }, text);\n    }\n    function element(tag, attrs = {}, ...children) {\n      const node = document.createElement(tag);\n      Object.entries(attrs).forEach(([key, value]) => node.setAttribute(key, value));\n      node.append(...children);\n      return node;\n    }\n    function choice(values) {\n      return values[Math.floor(Math.random() * values.length)];\n    }\n    function shuffle(values) {\n      const copy = values.slice();\n      for (let index = copy.length - 1; index > 0; index -= 1) {\n        const other = Math.floor(Math.random() * (index + 1));\n        [copy[index], copy[other]] = [copy[other], copy[index]];\n      }\n      return copy;\n    }\n  })();\n</script>\n\n\n## Using this lesson with edumath and SymPy\n\nUse `edumath` to compute confidence intervals.\n\n::: {#de821f83 .cell execution_count=1}\n``` {.python .cell-code}\nfrom edumath.statistics import confidence_interval_mean, confidence_interval_proportion\n\nconfidence_interval_mean([48, 52, 51, 49, 50], confidence_level=0.95)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nConfidenceInterval(estimate=50.0, lower=48.614096175650324, upper=51.385903824349676, margin_of_error=1.3859038243496775, confidence_level=0.95)\n```\n:::\n:::\n\n\n::: {#8c8c7a86 .cell execution_count=2}\n``` {.python .cell-code}\nconfidence_interval_proportion(60, 100)\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nConfidenceInterval(estimate=0.6, lower=0.5039817664728938, upper=0.6960182335271061, margin_of_error=0.09601823352710616, confidence_level=0.95)\n```\n:::\n:::\n\n\nUse SymPy to rearrange the interval formula.\n\n::: {#9d6a6e00 .cell execution_count=3}\n``` {.python .cell-code}\nimport sympy as sp\n\nestimate, critical, se = sp.symbols(\"estimate critical se\")\nlower = estimate - critical * se\nupper = estimate + critical * se\nsp.simplify(upper - lower)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=3}\n$\\displaystyle 2 \\mathcal{criti} se$\n:::\n:::\n\n\n",
    "supporting": ["estimation_files"],
    "filters": [],
    "includes": {}
  }
}
