{
  "hash": "04bf51ef21e263e98c93f5d43565d888",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Trigonometric Equations\ndescription: Solve sine, cosine, and tangent equations with the unit circle and periodicity.\nexecute:\n  echo: false\n---\n\nA trigonometric equation asks for angle values that make a trig statement true.\nUnlike many algebra equations, trig equations often have repeating answers. If\none angle works, every coterminal angle may also work.\n\nThe main idea is simple:\n\n::: {.formula-box}\n```text\nalgebra first, unit circle second, periodicity third\n```\n:::\n\n::: {.learning-objectives}\n### Learning objectives\n\nAfter this lesson you should be able to:\n\n- solve basic equations such as `sin(theta)=1/2`, `cos(theta)=0`, and\n  `tan(theta)=1`;\n- find all solutions in a requested interval;\n- write infinite solution families using periods;\n- isolate a trig function before using the unit circle;\n- check candidate solutions and reject extraneous ones;\n- use SymPy as a verification tool while still reasoning from the unit circle.\n:::\n\n## Why trig equations have many answers\n\nOn the unit circle, each angle gives a point `(cos(theta), sin(theta))`. Since a\nfull turn brings you back to the same point, trig values repeat.\n\nFor example:\n\n```text\nsin(30 degrees) = 1/2\nsin(150 degrees) = 1/2\nsin(390 degrees) = 1/2\n```\n\nThe angles `30 degrees` and `390 degrees` are coterminal, and `150 degrees` has\nthe same reference angle but is in a different quadrant.\n\n## The solving routine\n\nUse this routine whenever you see a trig equation.\n\n1. **Read the interval.** Are answers requested in degrees, radians, or all real\n   angles?\n2. **Isolate one trig expression.** For example, change `2cos(theta)-1=0` into\n   `cos(theta)=1/2`.\n3. **Find the reference angle.** Use special angles or inverse trig.\n4. **Choose quadrants using the sign.** Positive sine means Quadrants I or II;\n   negative cosine means Quadrants II or III; positive tangent means Quadrants I\n   or III.\n5. **List answers in the interval.** Do not stop after the first angle.\n6. **For all real solutions, add the period.** Sine and cosine repeat every\n   `360 degrees` or `2pi`; tangent repeats every `180 degrees` or `pi`.\n7. **Check.** Substitute each answer mentally, symbolically, or numerically.\n\n## Basic unit-circle equations\n\nSome equations can be read directly from the unit circle.\n\n```text\nsin(theta) = 0      -> theta is on the x-axis\ncos(theta) = 0      -> theta is on the y-axis\ntan(theta) = 0      -> sine is 0 and cosine is not 0\n```\n\nIn `[0,360)`:\n\n```text\nsin(theta)=0  -> 0, 180 degrees\ncos(theta)=0  -> 90, 270 degrees\ntan(theta)=0  -> 0, 180 degrees\n```\n\n## Reference angles and quadrants\n\nIf the equation uses a special value, first find the reference angle.\n\n```text\nsin(theta)=1/2      -> reference angle 30 degrees\ncos(theta)=sqrt(2)/2 -> reference angle 45 degrees\ntan(theta)=sqrt(3) -> reference angle 60 degrees\n```\n\nThen use signs.\n\n| Equation | Positive or negative? | Quadrants |\n|---|---:|---|\n| `sin(theta)=positive` | positive | I, II |\n| `sin(theta)=negative` | negative | III, IV |\n| `cos(theta)=positive` | positive | I, IV |\n| `cos(theta)=negative` | negative | II, III |\n| `tan(theta)=positive` | positive | I, III |\n| `tan(theta)=negative` | negative | II, IV |\n\n## Worked example 1: solve a sine equation in degrees\n\nSolve in `[0,360)`:\n\n```text\nsin(theta)=1/2\n```\n\n**Step 1: Identify the reference angle.**\n\n```text\nsin(30 degrees)=1/2\n```\n\nSo the reference angle is `30 degrees`.\n\n**Step 2: Decide the quadrants.**\n\nSine is positive because the right side is positive. Sine is positive in\nQuadrants I and II.\n\n**Step 3: Build the angles.**\n\n```text\nQuadrant I angle:  30 degrees\nQuadrant II angle: 180 - 30 = 150 degrees\n```\n\n**Answer:**\n\n```text\ntheta = 30 degrees or 150 degrees\n```\n\n**Check.** Both angles have y-coordinate `1/2` on the unit circle.\n\n## Worked example 2: isolate before solving\n\nSolve in `[0,2pi)`:\n\n```text\n2cos(theta) - 1 = 0\n```\n\n**Step 1: Isolate cosine.**\n\n```text\n2cos(theta) - 1 = 0\n2cos(theta) = 1\ncos(theta) = 1/2\n```\n\n**Step 2: Find the reference angle.**\n\n```text\ncos(pi/3)=1/2\n```\n\nThe reference angle is `pi/3`.\n\n**Step 3: Choose quadrants.**\n\nCosine is positive in Quadrants I and IV.\n\n**Step 4: List answers in `[0,2pi)`.**\n\n```text\nQuadrant I:  pi/3\nQuadrant IV: 2pi - pi/3 = 5pi/3\n```\n\n**Answer:**\n\n```text\ntheta = pi/3 or 5pi/3\n```\n\n## Worked example 3: write all real solutions\n\nSolve for all real `theta`:\n\n```text\ntan(theta)=1\n```\n\n**Step 1: Find one angle.**\n\n```text\ntan(45 degrees)=1\n```\n\nIn radians, that is `pi/4`.\n\n**Step 2: Use tangent's period.**\n\nTangent repeats every `pi`, not every `2pi`.\n\n**Answer:**\n\n```text\ntheta = pi/4 + k*pi, where k is any integer\n```\n\nThis compact formula includes `pi/4`, `5pi/4`, `-3pi/4`, and infinitely many\nmore.\n\n## Worked example 4: factor first\n\nSolve in `[0,360)`:\n\n```text\n2sin^2(theta) - sin(theta) = 0\n```\n\n**Step 1: Factor.**\n\n```text\n2sin^2(theta) - sin(theta)\n= sin(theta)(2sin(theta)-1)\n```\n\nSo:\n\n```text\nsin(theta)(2sin(theta)-1)=0\n```\n\n**Step 2: Use the zero product property.**\n\n```text\nsin(theta)=0\n```\n\nor\n\n```text\n2sin(theta)-1=0\nsin(theta)=1/2\n```\n\n**Step 3: Solve each equation.**\n\nFor `sin(theta)=0` in `[0,360)`:\n\n```text\ntheta = 0, 180 degrees\n```\n\nFor `sin(theta)=1/2` in `[0,360)`:\n\n```text\ntheta = 30, 150 degrees\n```\n\n**Answer:**\n\n```text\ntheta = 0, 30, 150, 180 degrees\n```\n\n## Common pitfalls\n\n- Forgetting to isolate the trig function before reading the unit circle.\n- Giving only the reference angle and missing the second quadrant solution.\n- Using sine/cosine period `2pi` for tangent; tangent's period is `pi`.\n- Mixing degrees and radians in the same answer.\n- Dividing by a trig expression that could be zero and losing solutions.\n- Including `360 degrees` in `[0,360)`; the square bracket/parenthesis means\n  `0` is included but `360` is not.\n\n## Practice exercises\n\n::: {.practice-box}\n1. Solve in `[0,360)`: `cos(theta)=1/2`.\n2. Solve in `[0,360)`: `sin(theta)=-1/2`.\n3. Solve in `[0,2pi)`: `tan(theta)=0`.\n4. Solve for all real `x`: `sin(x)=0`.\n5. Solve in `[0,360)`: `2cos(theta)+1=0`.\n6. Solve in `[0,360)`: `sin(theta)(sin(theta)-1)=0`.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions\n\n1. `cos(theta)=1/2` has reference angle `60 degrees`; cosine is positive in\n   Quadrants I and IV, so `theta=60, 300 degrees`.\n2. `sin(theta)=-1/2` has reference angle `30 degrees`; sine is negative in\n   Quadrants III and IV, so `theta=210, 330 degrees`.\n3. Tangent is zero where sine is zero and cosine is not zero: `x=0, pi`.\n4. `x=k*pi`, where `k` is any integer.\n5. `2cos(theta)+1=0` gives `cos(theta)=-1/2`; reference angle `60 degrees`,\n   Quadrants II and III, so `theta=120, 240 degrees`.\n6. `sin(theta)=0` or `sin(theta)=1`, so `theta=0, 180, 90 degrees`. In increasing\n   order: `0, 90, 180 degrees`.\n:::\n\n## Subtopic guided practice and checkpoints\n\nThese small labs separate the skills that are usually mixed together in a full\nproblem.\n\n### Lab 1: isolate first\n\n**Guess first.** What is the first algebra move in `3sin(theta)+2=5`?\n\n**Guided exercise.**\n\nSubtract `2`, then divide by `3`:\n\n```text\n3sin(theta)+2=5\n3sin(theta)=3\nsin(theta)=1\n```\n\nNow the unit circle can be used.\n\n::: {.practice-box}\n**Checkpoint.** Isolate the trig function in `4cos(theta)-2=0`.\n:::\n\n### Lab 2: find the reference angle\n\n**Guess first.** If `sin(theta)=sqrt(2)/2`, what special angle should you think\nof?\n\n**Guided exercise.**\n\nThe value `sqrt(2)/2` belongs to `45 degrees` or `pi/4`.\n\n::: {.practice-box}\n**Checkpoint.** What is the reference angle for `cos(theta)=sqrt(3)/2`?\n:::\n\n### Lab 3: choose all quadrants\n\n**Guess first.** If cosine is negative, which quadrants are possible?\n\n**Guided exercise.**\n\nCosine is the x-coordinate. It is negative on the left side of the unit circle,\nso Quadrants II and III are possible.\n\n::: {.practice-box}\n**Checkpoint.** If tangent is negative, which quadrants are possible?\n:::\n\n### Lab 4: write a periodic family\n\n**Guess first.** Does `cos(x)=1` repeat every `pi` or `2pi`?\n\n**Guided exercise.**\n\nCosine repeats every `2pi`, so all solutions are:\n\n```text\nx = 2k*pi, where k is any integer\n```\n\n::: {.practice-box}\n**Checkpoint.** Write all real solutions of `tan(x)=0`.\n:::\n\n### Lab 5: check the interval\n\n**Guess first.** Should `360 degrees` be included in `[0,360)`?\n\n**Guided exercise.**\n\nNo. The notation `[0,360)` means include `0` and exclude `360`. This avoids\ncounting the same direction twice.\n\n::: {.practice-box}\n**Checkpoint.** In `[0,2pi)`, should `2pi` be listed?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Lab checkpoint answers\n\n1. `cos(theta)=1/2`.\n2. `30 degrees` or `pi/6`.\n3. Quadrants II and IV.\n4. `x=k*pi`, where `k` is any integer.\n5. No, `2pi` is excluded from `[0,2pi)`.\n:::\n\n## Trig equation guessing game\n\n<script type=\"application/json\" class=\"edu-math-trigonometry-checkpoint-config\">\n{\n  \"topic\": \"trig-equations\",\n  \"title\": \"Trigonometric equations checkpoint\",\n  \"defaultTotal\": 5\n}\n</script>\n\n<div class=\"quiz-shell edu-math-trigonometry-checkpoint\" data-default-total=\"4\"></div>\n\n<script>\n  (() => {\n    const DEFAULT_TOPIC = \"unit-circle\";\n    const BANKS = {\n      \"radians-and-degrees\": [degreesRadiansQuestion, coterminalQuestion, referenceAngleQuestion, quadrantQuestion],\n      \"unit-circle\": [coordinateQuestion, signsQuestion, specialAngleQuestion, tangentQuestion],\n      \"sine-cosine\": [sineCoordinateQuestion, cosineCoordinateQuestion, rightTriangleQuestion, signQuestion],\n      \"trig-functions-and-graphs\": [amplitudeQuestion, periodQuestion, midlineQuestion, phaseQuestion],\n      identities: [pythagoreanIdentityQuestion, tangentIdentityQuestion, reciprocalQuestion, verifyIdentityQuestion],\n      \"trig-equations\": [basicSineEquationQuestion, basicCosineEquationQuestion, periodicQuestion, intervalQuestion],\n      applications: [rightTriangleQuestion, elevationQuestion, sinusoidQuestion, bearingQuestion],\n      \"trigonometry-cumulative-review\": [degreesRadiansQuestion, coordinateQuestion, specialAngleQuestion, amplitudeQuestion, pythagoreanIdentityQuestion, basicSineEquationQuestion],\n    };\n\n    document.querySelectorAll(\".edu-math-trigonometry-checkpoint:not([data-ready])\").forEach(init);\n\n    function init(root) {\n      const config = readConfig(root);\n      const state = { config, total: config.defaultTotal, index: 0, score: 0 };\n      root.dataset.ready = \"true\";\n      renderStart(root, state);\n    }\n\n    function readConfig(root) {\n      const node = root.previousElementSibling;\n      let parsed = {};\n      if (node?.classList?.contains(\"edu-math-trigonometry-checkpoint-config\")) {\n        try {\n          parsed = JSON.parse(node.textContent || \"{}\");\n        } catch {\n          parsed = {};\n        }\n      }\n      return {\n        topic: parsed.topic || root.dataset.topic || DEFAULT_TOPIC,\n        title: parsed.title || \"Trigonometry checkpoint\",\n        defaultTotal: Math.max(1, Math.min(20, Number(parsed.defaultTotal || 4))),\n      };\n    }\n\n    function renderStart(root, state) {\n      root.replaceChildren();\n      const input = element(\"input\", { class: \"quiz-count\", type: \"number\", min: \"1\", max: \"20\", value: String(state.total) });\n      const button = element(\"button\", { type: \"button\" }, \"Start checkpoint\");\n      button.addEventListener(\"click\", () => {\n        state.total = Math.max(1, Math.min(20, Number(input.value) || 4));\n        state.index = 0;\n        state.score = 0;\n        renderQuestion(root, state, makeQuestion(state.config.topic));\n      });\n      root.append(\n        element(\"p\", { class: \"quiz-topic\" }, state.config.title),\n        element(\"div\", { class: \"quiz-start\" }, element(\"label\", {}, element(\"span\", {}, \"Number of questions\"), input), button),\n      );\n    }\n\n    function renderQuestion(root, state, question) {\n      root.replaceChildren();\n      let answered = false;\n      const progress = element(\n        \"div\",\n        { class: \"quiz-progress\" },\n        element(\"span\", {}, `Question ${state.index + 1} of ${state.total}`),\n        element(\"span\", {}, `Score: ${state.score}/${state.total}`),\n      );\n      const feedback = element(\"p\", { class: \"quiz-feedback\", \"aria-live\": \"polite\" });\n      const next = element(\"button\", { type: \"button\", disabled: \"\" }, \"Next question\");\n      const options = radioList(question.options, (selected) => {\n        if (answered) return;\n        answered = true;\n        const correct = selected === question.answer;\n        if (correct) state.score += 1;\n        feedback.className = correct ? \"quiz-feedback correct\" : \"quiz-feedback wrong\";\n        feedback.replaceChildren(correct ? \"Correct.\" : `Not quite. The answer is ${question.answer}.`, \" \", question.explanation);\n        options.querySelectorAll(\"input\").forEach((input) => {\n          input.disabled = true;\n        });\n        progress.lastElementChild.textContent = `Score: ${state.score}/${state.total}`;\n        next.disabled = false;\n      });\n      next.addEventListener(\"click\", () => {\n        state.index += 1;\n        if (state.index >= state.total) renderDone(root, state);\n        else renderQuestion(root, state, makeQuestion(state.config.topic));\n      });\n      root.append(progress, stimulus(question.stimulus), element(\"p\", { class: \"quiz-prompt\" }, question.prompt), feedback, options, next);\n    }\n\n    function renderDone(root, state) {\n      root.replaceChildren();\n      const restart = element(\"button\", { type: \"button\" }, \"Try again\");\n      restart.addEventListener(\"click\", () => renderStart(root, state));\n      root.append(element(\"h3\", {}, \"Checkpoint complete\"), element(\"p\", {}, `Final score: ${state.score}/${state.total}`), restart);\n    }\n\n    function makeQuestion(topic) {\n      const bank = BANKS[topic] || BANKS[DEFAULT_TOPIC];\n      return choice(bank)();\n    }\n\n    function degreesRadiansQuestion() {\n      return question({ prompt: \"Convert 180 degrees to radians.\", stimulus: \"half turn\", answer: \"pi\", distractors: [\"2pi\", \"pi/2\", \"180pi\"], explanation: \"A full turn is 2pi radians, so a half turn is pi radians.\" });\n    }\n    function coterminalQuestion() {\n      return question({ prompt: \"Which angle is coterminal with -30 degrees in [0,360)?\", stimulus: \"add 360 degrees\", answer: \"330 degrees\", distractors: [\"30 degrees\", \"300 degrees\", \"-390 degrees\"], explanation: \"-30 + 360 = 330.\" });\n    }\n    function referenceAngleQuestion() {\n      return question({ prompt: \"What is the reference angle for 150 degrees?\", stimulus: \"Quadrant II\", answer: \"30 degrees\", distractors: [\"60 degrees\", \"150 degrees\", \"210 degrees\"], explanation: \"In Quadrant II, reference angle is 180 - theta.\" });\n    }\n    function quadrantQuestion() {\n      return question({ prompt: \"Which quadrant contains 240 degrees?\", stimulus: \"between 180 and 270\", answer: \"III\", distractors: [\"I\", \"II\", \"IV\"], explanation: \"Angles between 180 and 270 degrees are in Quadrant III.\" });\n    }\n    function coordinateQuestion() {\n      return question({ prompt: \"On the unit circle, which coordinate is sine?\", stimulus: \"point = (cos theta, sin theta)\", answer: \"vertical coordinate\", distractors: [\"horizontal coordinate\", \"radius length\", \"angle measure\"], explanation: \"Sine is the y-coordinate.\" });\n    }\n    function signsQuestion() {\n      return question({ prompt: \"In Quadrant II, what are the signs of sine and cosine?\", stimulus: \"x negative, y positive\", answer: \"sine positive, cosine negative\", distractors: [\"both positive\", \"both negative\", \"sine negative, cosine positive\"], explanation: \"Sine is y, cosine is x.\" });\n    }\n    function specialAngleQuestion() {\n      return question({ prompt: \"What is sin(30 degrees)?\", stimulus: \"special angle\", answer: \"1/2\", distractors: [\"sqrt(3)/2\", \"sqrt(2)/2\", \"1\"], explanation: \"The 30-60-90 triangle gives sin(30)=1/2.\" });\n    }\n    function tangentQuestion() {\n      return question({ prompt: \"What is tan(theta) in terms of sine and cosine?\", stimulus: \"tangent ratio\", answer: \"sin(theta)/cos(theta)\", distractors: [\"cos(theta)/sin(theta)\", \"1/sin(theta)\", \"sin(theta)+cos(theta)\"], explanation: \"Tangent is sine divided by cosine when cosine is not zero.\" });\n    }\n    function sineCoordinateQuestion() {\n      return question({ prompt: \"At 90 degrees, what is sine?\", stimulus: \"unit-circle point (0,1)\", answer: \"1\", distractors: [\"0\", \"-1\", \"undefined\"], explanation: \"The y-coordinate at 90 degrees is 1.\" });\n    }\n    function cosineCoordinateQuestion() {\n      return question({ prompt: \"At 180 degrees, what is cosine?\", stimulus: \"unit-circle point (-1,0)\", answer: \"-1\", distractors: [\"1\", \"0\", \"undefined\"], explanation: \"The x-coordinate at 180 degrees is -1.\" });\n    }\n    function rightTriangleQuestion() {\n      return question({ prompt: \"In a right triangle, sine equals which ratio?\", stimulus: \"SOH-CAH-TOA\", answer: \"opposite / hypotenuse\", distractors: [\"adjacent / hypotenuse\", \"opposite / adjacent\", \"hypotenuse / opposite\"], explanation: \"SOH means sine = opposite over hypotenuse.\" });\n    }\n    function signQuestion() {\n      return question({ prompt: \"At 300 degrees, is sine positive or negative?\", stimulus: \"Quadrant IV\", answer: \"negative\", distractors: [\"positive\", \"zero\", \"undefined\"], explanation: \"Quadrant IV has negative y-values, so sine is negative.\" });\n    }\n    function amplitudeQuestion() {\n      return question({ prompt: \"What is the amplitude of y = 3 sin(x)?\", stimulus: \"vertical stretch\", answer: \"3\", distractors: [\"1\", \"2pi\", \"pi\"], explanation: \"Amplitude is the absolute value of the coefficient in front of sine or cosine.\" });\n    }\n    function periodQuestion() {\n      return question({ prompt: \"What is the period of sin(x)?\", stimulus: \"basic sine wave\", answer: \"2pi\", distractors: [\"pi\", \"1\", \"4pi\"], explanation: \"Basic sine repeats every 2pi radians.\" });\n    }\n    function midlineQuestion() {\n      return question({ prompt: \"What is the midline of y = sin(x) + 4?\", stimulus: \"vertical shift\", answer: \"y = 4\", distractors: [\"y = 1\", \"y = -4\", \"x = 4\"], explanation: \"The +4 shifts the center line to y=4.\" });\n    }\n    function phaseQuestion() {\n      return question({ prompt: \"In y = sin(x - pi/2), which way is the graph shifted?\", stimulus: \"inside subtraction\", answer: \"right\", distractors: [\"left\", \"up\", \"down\"], explanation: \"Subtracting inside shifts the graph right.\" });\n    }\n    function pythagoreanIdentityQuestion() {\n      return question({ prompt: \"Complete the identity: sin^2(x) + cos^2(x) = ?\", stimulus: \"Pythagorean identity\", answer: \"1\", distractors: [\"0\", \"tan(x)\", \"2\"], explanation: \"The unit-circle point has distance 1 from the origin.\" });\n    }\n    function tangentIdentityQuestion() {\n      return question({ prompt: \"Which identity rewrites tan(x)?\", stimulus: \"quotient identity\", answer: \"sin(x)/cos(x)\", distractors: [\"cos(x)/sin(x)\", \"1/cos(x)\", \"1/sin(x)\"], explanation: \"tan(x)=sin(x)/cos(x).\" });\n    }\n    function reciprocalQuestion() {\n      return question({ prompt: \"Which reciprocal identity is correct?\", stimulus: \"secant\", answer: \"sec(x)=1/cos(x)\", distractors: [\"sec(x)=1/sin(x)\", \"sec(x)=sin(x)/cos(x)\", \"sec(x)=cos(x)\"], explanation: \"Secant is reciprocal cosine.\" });\n    }\n    function verifyIdentityQuestion() {\n      return question({ prompt: \"What is the safest first move when proving a trig identity?\", stimulus: \"identity strategy\", answer: \"rewrite one side using known identities\", distractors: [\"divide by zero\", \"change both sides randomly\", \"plug in one angle only\"], explanation: \"Use known identities and algebra to transform one side into the other.\" });\n    }\n    function basicSineEquationQuestion() {\n      return question({ prompt: \"In [0,360), solve sin(theta)=0.\", stimulus: \"x-axis intersections\", answer: \"0 and 180 degrees\", distractors: [\"90 and 270 degrees\", \"30 and 150 degrees\", \"45 and 225 degrees\"], explanation: \"Sine is y-coordinate, which is 0 on the x-axis.\" });\n    }\n    function basicCosineEquationQuestion() {\n      return question({ prompt: \"In [0,360), solve cos(theta)=0.\", stimulus: \"y-axis intersections\", answer: \"90 and 270 degrees\", distractors: [\"0 and 180 degrees\", \"30 and 330 degrees\", \"45 and 315 degrees\"], explanation: \"Cosine is x-coordinate, which is 0 on the y-axis.\" });\n    }\n    function periodicQuestion() {\n      return question({ prompt: \"Why can sin(theta)=1/2 have infinitely many solutions?\", stimulus: \"periodicity\", answer: \"sine repeats every full turn\", distractors: [\"sine is linear\", \"angles stop at 360\", \"cosine is undefined\"], explanation: \"Adding 360 degrees or 2pi radians gives coterminal solutions.\" });\n    }\n    function intervalQuestion() {\n      return question({ prompt: \"In [0,360), solve sin(theta)=1.\", stimulus: \"top of unit circle\", answer: \"90 degrees\", distractors: [\"0 degrees\", \"180 degrees\", \"270 degrees\"], explanation: \"The top of the unit circle is (0,1).\" });\n    }\n    function elevationQuestion() {\n      return question({ prompt: \"For angle of elevation, opposite side usually represents what?\", stimulus: \"right-triangle model\", answer: \"height\", distractors: [\"horizontal distance\", \"hypotenuse always\", \"angle measure\"], explanation: \"Height is vertical, opposite the ground angle.\" });\n    }\n    function sinusoidQuestion() {\n      return question({ prompt: \"Which trig function type models repeating seasonal behavior?\", stimulus: \"periodic data\", answer: \"sinusoidal\", distractors: [\"linear\", \"quadratic\", \"constant only\"], explanation: \"Sine and cosine model smooth repeating cycles.\" });\n    }\n    function bearingQuestion() {\n      return question({ prompt: \"A vector with components (3,4) has length?\", stimulus: \"right triangle\", answer: \"5\", distractors: [\"7\", \"1\", \"12\"], explanation: \"Use the Pythagorean theorem: sqrt(3^2+4^2)=5.\" });\n    }\n\n    function question({ prompt, stimulus, answer, distractors, explanation }) {\n      return { prompt, stimulus, answer, options: shuffle([answer, ...distractors]), explanation };\n    }\n    function radioList(options, onSelect) {\n      const name = `trigonometry-checkpoint-${Math.random().toString(36).slice(2)}`;\n      const container = element(\"div\", { class: \"quiz-options\" });\n      options.forEach((option) => {\n        const input = element(\"input\", { type: \"radio\", name, value: option });\n        input.addEventListener(\"change\", () => onSelect(option));\n        container.append(element(\"label\", {}, input, element(\"span\", {}, option)));\n      });\n      return container;\n    }\n    function stimulus(text) {\n      return element(\"pre\", { class: \"quiz-stimulus\" }, text);\n    }\n    function element(tag, attrs = {}, ...children) {\n      const node = document.createElement(tag);\n      Object.entries(attrs).forEach(([key, value]) => node.setAttribute(key, value));\n      node.append(...children);\n      return node;\n    }\n    function choice(values) {\n      return values[Math.floor(Math.random() * values.length)];\n    }\n    function shuffle(values) {\n      const copy = values.slice();\n      for (let index = copy.length - 1; index > 0; index -= 1) {\n        const other = Math.floor(Math.random() * (index + 1));\n        [copy[index], copy[other]] = [copy[other], copy[index]];\n      }\n      return copy;\n    }\n  })();\n</script>\n\n\n## Using this lesson with edumath and SymPy\n\nUse `edumath` for angle facts and SymPy for algebraic verification. SymPy can\nsolve many equations, but interval reasoning is still easier when you understand\nthe unit circle.\n\n::: {#7ee61f0b .cell execution_count=1}\n``` {.python .cell-code}\nfrom edumath.trigonometry import reference_angle_degrees, trig_signs\n\nreference_angle_degrees(150)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n30\n```\n:::\n:::\n\n\n::: {#64b5494d .cell execution_count=2}\n``` {.python .cell-code}\ntrig_signs(150)\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n{'sine': '+', 'cosine': '-', 'tangent': '-'}\n```\n:::\n:::\n\n\nUse SymPy to solve or verify exact equations.\n\n::: {#bf7d3418 .cell execution_count=3}\n``` {.python .cell-code}\nimport sympy as sp\n\ntheta = sp.symbols(\"theta\")\nsp.solve(sp.Eq(2 * sp.cos(theta) - 1, 0), theta)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n[pi/3, 5*pi/3]\n```\n:::\n:::\n\n\nFor all real solutions, SymPy's `solveset` gives a set description.\n\n::: {#38a3b2d1 .cell execution_count=4}\n``` {.python .cell-code}\nsp.solveset(sp.Eq(sp.sin(theta), sp.Rational(1, 2)), theta, domain=sp.S.Reals)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n$\\displaystyle \\left\\{2 n \\pi + \\frac{\\pi}{6}\\; \\middle|\\; n \\in \\mathbb{Z}\\right\\} \\cup \\left\\{2 n \\pi + \\frac{5 \\pi}{6}\\; \\middle|\\; n \\in \\mathbb{Z}\\right\\}$\n:::\n:::\n\n\n",
    "supporting": ["trig-equations_files"],
    "filters": [],
    "includes": {}
  }
}
