{
  "hash": "244520780e3c0d83b2ce3a66dbffc55e",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: The Unit Circle\ndescription: Sine, cosine, tangent, quadrants, signs, and reference angles on the unit circle.\nexecute:\n  echo: false\n---\n\nThe unit circle is a circle of radius `1` centered at the origin. It turns\ntrigonometry into coordinate geometry. When an angle starts on the positive\nx-axis and rotates around the circle, the point where it lands has coordinates:\n\n```text\n(cos(theta), sin(theta))\n```\n\n::: {.learning-objectives}\n### Learning objectives\n\nAfter this lesson you should be able to:\n\n- read cosine as the horizontal coordinate;\n- read sine as the vertical coordinate;\n- find tangent as `sin(theta)/cos(theta)`;\n- use quadrants to determine signs;\n- use reference angles to find related trig values;\n- use a unit-circle plot to check values.\n:::\n\n## Coordinates on the circle\n\nFor any angle `theta`, the unit-circle point is:\n\n```text\nx = cos(theta)\ny = sin(theta)\n```\n\nBecause the radius is 1, every point satisfies:\n\n```text\nx^2 + y^2 = 1\n```\n\nReplacing `x` with cosine and `y` with sine gives the identity:\n\n```text\ncos^2(theta) + sin^2(theta) = 1\n```\n\n## Axis angles\n\nSome angles land exactly on an axis.\n\n| angle | point | cosine | sine |\n|---:|---:|---:|---:|\n| `0 degrees` | `(1,0)` | `1` | `0` |\n| `90 degrees` | `(0,1)` | `0` | `1` |\n| `180 degrees` | `(-1,0)` | `-1` | `0` |\n| `270 degrees` | `(0,-1)` | `0` | `-1` |\n| `360 degrees` | `(1,0)` | `1` | `0` |\n\n## Quadrants and signs\n\nThe quadrant tells the signs of sine and cosine.\n\n| Quadrant | x-coordinate | y-coordinate | cosine | sine | tangent |\n|---|---:|---:|---:|---:|---:|\n| I | positive | positive | + | + | + |\n| II | negative | positive | - | + | - |\n| III | negative | negative | - | - | + |\n| IV | positive | negative | + | - | - |\n\nA useful memory phrase is **All Students Take Calculus**:\n\n- Quadrant I: all positive;\n- Quadrant II: sine positive;\n- Quadrant III: tangent positive;\n- Quadrant IV: cosine positive.\n\n## Special angles\n\nThe most common reference angles are `30`, `45`, and `60` degrees.\n\n| angle | sine | cosine | tangent |\n|---:|---:|---:|---:|\n| `30°` | `1/2` | `sqrt(3)/2` | `sqrt(3)/3` |\n| `45°` | `sqrt(2)/2` | `sqrt(2)/2` | `1` |\n| `60°` | `sqrt(3)/2` | `1/2` | `sqrt(3)` |\n\nUse the reference angle for size and the quadrant for sign.\n\n## Tangent on the unit circle\n\nTangent is the ratio:\n\n```text\ntan(theta) = sin(theta) / cos(theta)\n```\n\nTangent is undefined when `cos(theta)=0`, because division by zero is not\nallowed. That happens at `90 degrees` and `270 degrees`.\n\n## Worked example 1: locate an angle\n\nFind the signs of sine, cosine, and tangent at `150 degrees`.\n\n1. `150 degrees` is in Quadrant II.\n2. In Quadrant II, x is negative and y is positive.\n3. Therefore cosine is negative and sine is positive.\n4. Tangent is sine divided by cosine, so tangent is negative.\n\n## Worked example 2: exact value\n\nFind `sin(150 degrees)`.\n\n1. The reference angle is `180 - 150 = 30 degrees`.\n2. `sin(30 degrees)=1/2`.\n3. `150 degrees` is in Quadrant II, where sine is positive.\n4. So `sin(150 degrees)=1/2`.\n\n## Common pitfalls\n\n- Swapping sine and cosine coordinates.\n- Forgetting signs in quadrants II, III, and IV.\n- Saying tangent is defined when cosine is zero.\n- Memorizing values without understanding reference angles.\n- Forgetting coterminal angles such as `390 degrees` and `30 degrees`.\n\n## Practice exercises\n\n::: {.practice-box}\n1. What is the unit-circle point at `90 degrees`?\n2. In Quadrant III, what are the signs of sine and cosine?\n3. Find the reference angle for `300 degrees`.\n4. Find `cos(120 degrees)`.\n5. Where is tangent undefined in `[0,360)`?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions\n\n1. `(0,1)`.\n2. Both sine and cosine are negative.\n3. `360-300=60 degrees`.\n4. Reference angle `60`; Quadrant II cosine is negative, so `cos(120)=-1/2`.\n5. `90 degrees` and `270 degrees`.\n:::\n\n## Subtopic guided practice and checkpoints\n\nUse this order: locate the angle, find the reference angle, choose signs, then\nuse the special-angle value.\n\n### Lab 1: read coordinates\n\n**Guess first.** At `0 degrees`, is the point on the right or top of the circle?\n\n**Guided exercise.**\n\nAt `0 degrees`, the radius points right to `(1,0)`. Therefore:\n\n```text\ncos(0)=1\nsin(0)=0\n```\n\n::: {.practice-box}\n**Checkpoint.** Find `sin(270 degrees)` and `cos(270 degrees)`.\n:::\n\n### Lab 2: use signs from quadrants\n\n**Guess first.** At `225 degrees`, should sine be positive or negative?\n\n**Guided exercise.**\n\n`225 degrees` is in Quadrant III. In Quadrant III, y is negative, so sine is\nnegative. x is also negative, so cosine is negative.\n\n::: {.practice-box}\n**Checkpoint.** Give the signs of sine, cosine, and tangent at `315 degrees`.\n:::\n\n### Lab 3: use reference angles\n\n**Guess first.** Does `210 degrees` have the same reference angle as `30 degrees`?\n\n**Guided exercise.**\n\n`210 degrees` is in Quadrant III. Its reference angle is:\n\n```text\n210 - 180 = 30 degrees\n```\n\nSo the size of sine and cosine matches `30 degrees`, but the signs are Quadrant\nIII signs.\n\n::: {.practice-box}\n**Checkpoint.** Find `sin(210 degrees)`.\n:::\n\n### Lab 4: tangent as a ratio\n\n**Guess first.** If sine and cosine have opposite signs, what sign does tangent\nhave?\n\n**Guided exercise.**\n\nTangent is sine divided by cosine. A positive divided by a negative is negative,\nand a negative divided by a positive is negative.\n\n::: {.practice-box}\n**Checkpoint.** Find `tan(225 degrees)`.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Lab checkpoint answers\n\n1. `sin(270)=-1` and `cos(270)=0`.\n2. At `315 degrees`, sine is negative, cosine is positive, and tangent is\n   negative.\n3. `sin(210)=-1/2`.\n4. Reference angle `45`, Quadrant III tangent is positive, so `tan(225)=1`.\n:::\n\n## Unit-circle guessing game\n\n<script type=\"application/json\" class=\"edu-math-trigonometry-checkpoint-config\">\n{\n  \"topic\": \"unit-circle\",\n  \"title\": \"Unit circle checkpoint\",\n  \"defaultTotal\": 4\n}\n</script>\n\n<div class=\"quiz-shell edu-math-trigonometry-checkpoint\" data-default-total=\"4\"></div>\n\n<script>\n  (() => {\n    const DEFAULT_TOPIC = \"unit-circle\";\n    const BANKS = {\n      \"radians-and-degrees\": [degreesRadiansQuestion, coterminalQuestion, referenceAngleQuestion, quadrantQuestion],\n      \"unit-circle\": [coordinateQuestion, signsQuestion, specialAngleQuestion, tangentQuestion],\n      \"sine-cosine\": [sineCoordinateQuestion, cosineCoordinateQuestion, rightTriangleQuestion, signQuestion],\n      \"trig-functions-and-graphs\": [amplitudeQuestion, periodQuestion, midlineQuestion, phaseQuestion],\n      identities: [pythagoreanIdentityQuestion, tangentIdentityQuestion, reciprocalQuestion, verifyIdentityQuestion],\n      \"trig-equations\": [basicSineEquationQuestion, basicCosineEquationQuestion, periodicQuestion, intervalQuestion],\n      applications: [rightTriangleQuestion, elevationQuestion, sinusoidQuestion, bearingQuestion],\n      \"trigonometry-cumulative-review\": [degreesRadiansQuestion, coordinateQuestion, specialAngleQuestion, amplitudeQuestion, pythagoreanIdentityQuestion, basicSineEquationQuestion],\n    };\n\n    document.querySelectorAll(\".edu-math-trigonometry-checkpoint:not([data-ready])\").forEach(init);\n\n    function init(root) {\n      const config = readConfig(root);\n      const state = { config, total: config.defaultTotal, index: 0, score: 0 };\n      root.dataset.ready = \"true\";\n      renderStart(root, state);\n    }\n\n    function readConfig(root) {\n      const node = root.previousElementSibling;\n      let parsed = {};\n      if (node?.classList?.contains(\"edu-math-trigonometry-checkpoint-config\")) {\n        try {\n          parsed = JSON.parse(node.textContent || \"{}\");\n        } catch {\n          parsed = {};\n        }\n      }\n      return {\n        topic: parsed.topic || root.dataset.topic || DEFAULT_TOPIC,\n        title: parsed.title || \"Trigonometry checkpoint\",\n        defaultTotal: Math.max(1, Math.min(20, Number(parsed.defaultTotal || 4))),\n      };\n    }\n\n    function renderStart(root, state) {\n      root.replaceChildren();\n      const input = element(\"input\", { class: \"quiz-count\", type: \"number\", min: \"1\", max: \"20\", value: String(state.total) });\n      const button = element(\"button\", { type: \"button\" }, \"Start checkpoint\");\n      button.addEventListener(\"click\", () => {\n        state.total = Math.max(1, Math.min(20, Number(input.value) || 4));\n        state.index = 0;\n        state.score = 0;\n        renderQuestion(root, state, makeQuestion(state.config.topic));\n      });\n      root.append(\n        element(\"p\", { class: \"quiz-topic\" }, state.config.title),\n        element(\"div\", { class: \"quiz-start\" }, element(\"label\", {}, element(\"span\", {}, \"Number of questions\"), input), button),\n      );\n    }\n\n    function renderQuestion(root, state, question) {\n      root.replaceChildren();\n      let answered = false;\n      const progress = element(\n        \"div\",\n        { class: \"quiz-progress\" },\n        element(\"span\", {}, `Question ${state.index + 1} of ${state.total}`),\n        element(\"span\", {}, `Score: ${state.score}/${state.total}`),\n      );\n      const feedback = element(\"p\", { class: \"quiz-feedback\", \"aria-live\": \"polite\" });\n      const next = element(\"button\", { type: \"button\", disabled: \"\" }, \"Next question\");\n      const options = radioList(question.options, (selected) => {\n        if (answered) return;\n        answered = true;\n        const correct = selected === question.answer;\n        if (correct) state.score += 1;\n        feedback.className = correct ? \"quiz-feedback correct\" : \"quiz-feedback wrong\";\n        feedback.replaceChildren(correct ? \"Correct.\" : `Not quite. The answer is ${question.answer}.`, \" \", question.explanation);\n        options.querySelectorAll(\"input\").forEach((input) => {\n          input.disabled = true;\n        });\n        progress.lastElementChild.textContent = `Score: ${state.score}/${state.total}`;\n        next.disabled = false;\n      });\n      next.addEventListener(\"click\", () => {\n        state.index += 1;\n        if (state.index >= state.total) renderDone(root, state);\n        else renderQuestion(root, state, makeQuestion(state.config.topic));\n      });\n      root.append(progress, stimulus(question.stimulus), element(\"p\", { class: \"quiz-prompt\" }, question.prompt), feedback, options, next);\n    }\n\n    function renderDone(root, state) {\n      root.replaceChildren();\n      const restart = element(\"button\", { type: \"button\" }, \"Try again\");\n      restart.addEventListener(\"click\", () => renderStart(root, state));\n      root.append(element(\"h3\", {}, \"Checkpoint complete\"), element(\"p\", {}, `Final score: ${state.score}/${state.total}`), restart);\n    }\n\n    function makeQuestion(topic) {\n      const bank = BANKS[topic] || BANKS[DEFAULT_TOPIC];\n      return choice(bank)();\n    }\n\n    function degreesRadiansQuestion() {\n      return question({ prompt: \"Convert 180 degrees to radians.\", stimulus: \"half turn\", answer: \"pi\", distractors: [\"2pi\", \"pi/2\", \"180pi\"], explanation: \"A full turn is 2pi radians, so a half turn is pi radians.\" });\n    }\n    function coterminalQuestion() {\n      return question({ prompt: \"Which angle is coterminal with -30 degrees in [0,360)?\", stimulus: \"add 360 degrees\", answer: \"330 degrees\", distractors: [\"30 degrees\", \"300 degrees\", \"-390 degrees\"], explanation: \"-30 + 360 = 330.\" });\n    }\n    function referenceAngleQuestion() {\n      return question({ prompt: \"What is the reference angle for 150 degrees?\", stimulus: \"Quadrant II\", answer: \"30 degrees\", distractors: [\"60 degrees\", \"150 degrees\", \"210 degrees\"], explanation: \"In Quadrant II, reference angle is 180 - theta.\" });\n    }\n    function quadrantQuestion() {\n      return question({ prompt: \"Which quadrant contains 240 degrees?\", stimulus: \"between 180 and 270\", answer: \"III\", distractors: [\"I\", \"II\", \"IV\"], explanation: \"Angles between 180 and 270 degrees are in Quadrant III.\" });\n    }\n    function coordinateQuestion() {\n      return question({ prompt: \"On the unit circle, which coordinate is sine?\", stimulus: \"point = (cos theta, sin theta)\", answer: \"vertical coordinate\", distractors: [\"horizontal coordinate\", \"radius length\", \"angle measure\"], explanation: \"Sine is the y-coordinate.\" });\n    }\n    function signsQuestion() {\n      return question({ prompt: \"In Quadrant II, what are the signs of sine and cosine?\", stimulus: \"x negative, y positive\", answer: \"sine positive, cosine negative\", distractors: [\"both positive\", \"both negative\", \"sine negative, cosine positive\"], explanation: \"Sine is y, cosine is x.\" });\n    }\n    function specialAngleQuestion() {\n      return question({ prompt: \"What is sin(30 degrees)?\", stimulus: \"special angle\", answer: \"1/2\", distractors: [\"sqrt(3)/2\", \"sqrt(2)/2\", \"1\"], explanation: \"The 30-60-90 triangle gives sin(30)=1/2.\" });\n    }\n    function tangentQuestion() {\n      return question({ prompt: \"What is tan(theta) in terms of sine and cosine?\", stimulus: \"tangent ratio\", answer: \"sin(theta)/cos(theta)\", distractors: [\"cos(theta)/sin(theta)\", \"1/sin(theta)\", \"sin(theta)+cos(theta)\"], explanation: \"Tangent is sine divided by cosine when cosine is not zero.\" });\n    }\n    function sineCoordinateQuestion() {\n      return question({ prompt: \"At 90 degrees, what is sine?\", stimulus: \"unit-circle point (0,1)\", answer: \"1\", distractors: [\"0\", \"-1\", \"undefined\"], explanation: \"The y-coordinate at 90 degrees is 1.\" });\n    }\n    function cosineCoordinateQuestion() {\n      return question({ prompt: \"At 180 degrees, what is cosine?\", stimulus: \"unit-circle point (-1,0)\", answer: \"-1\", distractors: [\"1\", \"0\", \"undefined\"], explanation: \"The x-coordinate at 180 degrees is -1.\" });\n    }\n    function rightTriangleQuestion() {\n      return question({ prompt: \"In a right triangle, sine equals which ratio?\", stimulus: \"SOH-CAH-TOA\", answer: \"opposite / hypotenuse\", distractors: [\"adjacent / hypotenuse\", \"opposite / adjacent\", \"hypotenuse / opposite\"], explanation: \"SOH means sine = opposite over hypotenuse.\" });\n    }\n    function signQuestion() {\n      return question({ prompt: \"At 300 degrees, is sine positive or negative?\", stimulus: \"Quadrant IV\", answer: \"negative\", distractors: [\"positive\", \"zero\", \"undefined\"], explanation: \"Quadrant IV has negative y-values, so sine is negative.\" });\n    }\n    function amplitudeQuestion() {\n      return question({ prompt: \"What is the amplitude of y = 3 sin(x)?\", stimulus: \"vertical stretch\", answer: \"3\", distractors: [\"1\", \"2pi\", \"pi\"], explanation: \"Amplitude is the absolute value of the coefficient in front of sine or cosine.\" });\n    }\n    function periodQuestion() {\n      return question({ prompt: \"What is the period of sin(x)?\", stimulus: \"basic sine wave\", answer: \"2pi\", distractors: [\"pi\", \"1\", \"4pi\"], explanation: \"Basic sine repeats every 2pi radians.\" });\n    }\n    function midlineQuestion() {\n      return question({ prompt: \"What is the midline of y = sin(x) + 4?\", stimulus: \"vertical shift\", answer: \"y = 4\", distractors: [\"y = 1\", \"y = -4\", \"x = 4\"], explanation: \"The +4 shifts the center line to y=4.\" });\n    }\n    function phaseQuestion() {\n      return question({ prompt: \"In y = sin(x - pi/2), which way is the graph shifted?\", stimulus: \"inside subtraction\", answer: \"right\", distractors: [\"left\", \"up\", \"down\"], explanation: \"Subtracting inside shifts the graph right.\" });\n    }\n    function pythagoreanIdentityQuestion() {\n      return question({ prompt: \"Complete the identity: sin^2(x) + cos^2(x) = ?\", stimulus: \"Pythagorean identity\", answer: \"1\", distractors: [\"0\", \"tan(x)\", \"2\"], explanation: \"The unit-circle point has distance 1 from the origin.\" });\n    }\n    function tangentIdentityQuestion() {\n      return question({ prompt: \"Which identity rewrites tan(x)?\", stimulus: \"quotient identity\", answer: \"sin(x)/cos(x)\", distractors: [\"cos(x)/sin(x)\", \"1/cos(x)\", \"1/sin(x)\"], explanation: \"tan(x)=sin(x)/cos(x).\" });\n    }\n    function reciprocalQuestion() {\n      return question({ prompt: \"Which reciprocal identity is correct?\", stimulus: \"secant\", answer: \"sec(x)=1/cos(x)\", distractors: [\"sec(x)=1/sin(x)\", \"sec(x)=sin(x)/cos(x)\", \"sec(x)=cos(x)\"], explanation: \"Secant is reciprocal cosine.\" });\n    }\n    function verifyIdentityQuestion() {\n      return question({ prompt: \"What is the safest first move when proving a trig identity?\", stimulus: \"identity strategy\", answer: \"rewrite one side using known identities\", distractors: [\"divide by zero\", \"change both sides randomly\", \"plug in one angle only\"], explanation: \"Use known identities and algebra to transform one side into the other.\" });\n    }\n    function basicSineEquationQuestion() {\n      return question({ prompt: \"In [0,360), solve sin(theta)=0.\", stimulus: \"x-axis intersections\", answer: \"0 and 180 degrees\", distractors: [\"90 and 270 degrees\", \"30 and 150 degrees\", \"45 and 225 degrees\"], explanation: \"Sine is y-coordinate, which is 0 on the x-axis.\" });\n    }\n    function basicCosineEquationQuestion() {\n      return question({ prompt: \"In [0,360), solve cos(theta)=0.\", stimulus: \"y-axis intersections\", answer: \"90 and 270 degrees\", distractors: [\"0 and 180 degrees\", \"30 and 330 degrees\", \"45 and 315 degrees\"], explanation: \"Cosine is x-coordinate, which is 0 on the y-axis.\" });\n    }\n    function periodicQuestion() {\n      return question({ prompt: \"Why can sin(theta)=1/2 have infinitely many solutions?\", stimulus: \"periodicity\", answer: \"sine repeats every full turn\", distractors: [\"sine is linear\", \"angles stop at 360\", \"cosine is undefined\"], explanation: \"Adding 360 degrees or 2pi radians gives coterminal solutions.\" });\n    }\n    function intervalQuestion() {\n      return question({ prompt: \"In [0,360), solve sin(theta)=1.\", stimulus: \"top of unit circle\", answer: \"90 degrees\", distractors: [\"0 degrees\", \"180 degrees\", \"270 degrees\"], explanation: \"The top of the unit circle is (0,1).\" });\n    }\n    function elevationQuestion() {\n      return question({ prompt: \"For angle of elevation, opposite side usually represents what?\", stimulus: \"right-triangle model\", answer: \"height\", distractors: [\"horizontal distance\", \"hypotenuse always\", \"angle measure\"], explanation: \"Height is vertical, opposite the ground angle.\" });\n    }\n    function sinusoidQuestion() {\n      return question({ prompt: \"Which trig function type models repeating seasonal behavior?\", stimulus: \"periodic data\", answer: \"sinusoidal\", distractors: [\"linear\", \"quadratic\", \"constant only\"], explanation: \"Sine and cosine model smooth repeating cycles.\" });\n    }\n    function bearingQuestion() {\n      return question({ prompt: \"A vector with components (3,4) has length?\", stimulus: \"right triangle\", answer: \"5\", distractors: [\"7\", \"1\", \"12\"], explanation: \"Use the Pythagorean theorem: sqrt(3^2+4^2)=5.\" });\n    }\n\n    function question({ prompt, stimulus, answer, distractors, explanation }) {\n      return { prompt, stimulus, answer, options: shuffle([answer, ...distractors]), explanation };\n    }\n    function radioList(options, onSelect) {\n      const name = `trigonometry-checkpoint-${Math.random().toString(36).slice(2)}`;\n      const container = element(\"div\", { class: \"quiz-options\" });\n      options.forEach((option) => {\n        const input = element(\"input\", { type: \"radio\", name, value: option });\n        input.addEventListener(\"change\", () => onSelect(option));\n        container.append(element(\"label\", {}, input, element(\"span\", {}, option)));\n      });\n      return container;\n    }\n    function stimulus(text) {\n      return element(\"pre\", { class: \"quiz-stimulus\" }, text);\n    }\n    function element(tag, attrs = {}, ...children) {\n      const node = document.createElement(tag);\n      Object.entries(attrs).forEach(([key, value]) => node.setAttribute(key, value));\n      node.append(...children);\n      return node;\n    }\n    function choice(values) {\n      return values[Math.floor(Math.random() * values.length)];\n    }\n    function shuffle(values) {\n      const copy = values.slice();\n      for (let index = copy.length - 1; index > 0; index -= 1) {\n        const other = Math.floor(Math.random() * (index + 1));\n        [copy[index], copy[other]] = [copy[other], copy[index]];\n      }\n      return copy;\n    }\n  })();\n</script>\n\n\n## Using this lesson with edumath and SymPy\n\nUse `edumath` to find quadrants, signs, and special-angle values.\n\n::: {#585bb8a7 .cell execution_count=1}\n``` {.python .cell-code}\nfrom edumath.trigonometry import quadrant, special_angle_values, trig_signs\n\nprint(quadrant(210))\nprint(trig_signs(210))\nprint(special_angle_values(30))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIII\n{'sine': '-', 'cosine': '-', 'tangent': '+'}\nExactTrigValues(sine='1/2', cosine='sqrt(3)/2', tangent='sqrt(3)/3')\n```\n:::\n:::\n\n\nUse the plotting helper for a unit-circle picture.\n\n::: {#6ad1319a .cell execution_count=2}\n``` {.python .cell-code}\nfrom edumath.trigonometry import plot_unit_circle\n\nfig, ax = plot_unit_circle(150)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n![](unit-circle_files/figure-html/cell-3-output-1.png){width=683 height=683}\n:::\n\n::: {.cell-output .cell-output-display}\n![](unit-circle_files/figure-html/cell-3-output-2.png){width=683 height=683}\n:::\n:::\n\n\nUse SymPy for exact values.\n\n::: {#42ecfbfb .cell execution_count=3}\n``` {.python .cell-code}\nimport sympy as sp\n\nsp.sin(5 * sp.pi / 6), sp.cos(5 * sp.pi / 6), sp.tan(5 * sp.pi / 4)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n(1/2, -sqrt(3)/2, 1)\n```\n:::\n:::\n\n\n",
    "supporting": ["unit-circle_files"],
    "filters": [],
    "includes": {}
  }
}
