#!/usr/bin/env python3
"""Generate learner navigation and browser manifests from the curriculum catalog."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from fcmath.validation import load_structured_data, validate_catalog

CATALOG = ROOT / "docs" / "courses" / "_catalog.yml"
SIDEBAR = ROOT / "docs" / "_sidebar.yml"
QUARTO = ROOT / "docs" / "_quarto.yml"
MAP = ROOT / "docs" / "assets" / "curriculum-map.json"
NAVIGATION = ROOT / "docs" / "assets" / "navigation.json"
PREREQUISITES = ROOT / "docs" / "assets" / "prerequisites.json"
CARDS = ROOT / "docs" / "courses" / "_cards.qmd"


def generated_files(catalog: dict[str, Any]) -> dict[Path, str]:
    """Return every generated file and its deterministic content."""

    pages: dict[str, str] = {}
    sequence: list[dict[str, str | None]] = []
    sidebar = [
        "# Generated by scripts/generate_navigation.py; do not edit.",
        "- index.qmd",
        "- section: Courses",
        "  contents:",
        "    - courses/index.qmd",
    ]
    cards = [
        "<!-- Generated by scripts/generate_navigation.py; do not edit. -->",
        "::: {.course-card-grid}",
    ]
    for course in catalog["courses"]:
        course_path = f"courses/{course['id']}/index.qmd"
        sidebar.extend(
            (
                f"    - section: {yaml_scalar(course['title'])}",
                "      contents:",
                f"        - {course_path}",
            )
        )
        item_count = int(course.get("item_count", 0))
        card_metadata = (
            f"**{len(course['units'])} unit(s) · {item_count} activities · "
            f"{course['status']}**"
        )
        cards.extend(
            (
                f"### [{course['title']}](courses/{course['id']}/index.qmd)",
                "",
                course["description"],
                "",
                card_metadata,
                "",
            )
        )
        for unit in course["units"]:
            sidebar.append(f"        - section: {yaml_scalar(unit['title'])}")
            sidebar.append("          contents:")
            sidebar.append(f"            - {unit['overview']}")
            unit_items = sorted(
                [*unit["lessons"], *unit["challenges"]],
                key=lambda item: item["order"],
            )
            for item in unit_items:
                sidebar.append(f"            - {item['file']}")
                pages[item["file"]] = item["id"]
                sequence.append(
                    {
                        "id": item["id"],
                        "file": item["file"],
                        "title": item["title"],
                        "course_id": course["id"],
                    }
                )
            for assessment_id in unit.get("assessment_ids", []):
                assessment = next(
                    item
                    for item in catalog["assessments"]
                    if item["id"] == assessment_id
                )
                sidebar.append(f"            - {assessment['file']}")
                pages[assessment["file"]] = assessment["id"]
                sequence.append(
                    {
                        "id": assessment["id"],
                        "file": assessment["file"],
                        "title": assessment["id"].replace("-", " ").title(),
                        "course_id": course["id"],
                    }
                )
    cards.append(":::")
    for assessment in catalog.get("assessments", []):
        pages.setdefault(assessment["file"], assessment["id"])
    sidebar.extend(
        (
            "- section: Resources",
            "  contents:",
            "    - resources/index.qmd",
            "    - resources/notation/index.qmd",
            "    - resources/formula-reference/index.qmd",
            "    - resources/computational-setup/index.qmd",
            "    - resources/study-guidance/index.qmd",
            "    - resources/faq/index.qmd",
            "- section: About",
            "  contents:",
            "    - about/index.qmd",
            "    - about/contributing.qmd",
            "- section: Developers",
            "  contents:",
            "    - developers/installation.qmd",
            "    - developers/api.qmd",
            "    - changelog.qmd",
        )
    )

    adjacent: dict[str, dict[str, str | None]] = {}
    for index, item in enumerate(sequence):
        previous = sequence[index - 1] if index else None
        following = sequence[index + 1] if index + 1 < len(sequence) else None
        adjacent[str(item["id"])] = {
            "file": item["file"],
            "previous_id": (
                previous["id"]
                if previous and previous["course_id"] == item["course_id"]
                else None
            ),
            "next_id": (
                following["id"]
                if following and following["course_id"] == item["course_id"]
                else None
            ),
        }
    page_manifest = {
        "schemaVersion": catalog["schema_version"],
        "curriculumVersion": catalog["curriculum_version"],
        "pages": pages,
        "notebooks": {
            source: f"https://colab.research.google.com/github/freecampus/math/blob/main/notebooks/{source.removesuffix('.qmd')}.ipynb"
            for source in pages
        },
    }
    prerequisites = {
        "schemaVersion": 1,
        "courses": {
            course["id"]: course["prerequisite_ids"] for course in catalog["courses"]
        },
    }
    sidebar_contents = "\n".join(
        f"      {line}" if line else line for line in sidebar[1:]
    )
    generation_comment = (
        "# Generated by scripts/generate_navigation.py; do not edit navigation by hand."
    )
    site_description = (
        "Proof-aware mathematics courses joining theory, manual problem solving, "
        "computation, and interpretation."
    )
    footer_privacy = (
        "Progress remains in your browser; no account or analytics profile is required."
    )
    quarto = f"""{generation_comment}
project:
  type: website
  output-dir: ../build
  resources:
    - courses/_catalog.yml
    - quizzes/**/*.yml
    - assets/*.json
  pre-render:
    - python ../scripts/validate_curriculum.py

brand: _brand.yml

website:
  title: FreeCampus Math
  description: {site_description}
  site-url: https://freecampus.github.io/math/
  repo-url: https://github.com/freecampus/math
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    logo: assets/brand/logo.svg
    logo-alt: FreeCampus Math
    left:
      - href: courses/index.qmd
        text: Browse courses
      - href: resources/index.qmd
        text: Resources
      - href: about/index.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/freecampus/math
        aria-label: FreeCampus Math source repository
  sidebar:
    style: docked
    search: true
    collapse-level: 2
    contents:
{sidebar_contents}
  page-footer:
    left: FreeCampus Math — open, institution-independent mathematics education.
    right: {footer_privacy}

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    include-in-header: _partials/head.html
    include-before-body: _partials/before-body.html
    include-after-body: _partials/scripts.html
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    anchor-sections: true

execute:
  freeze: false
  echo: false
"""
    outputs = {
        SIDEBAR: "\n".join(sidebar) + "\n",
        QUARTO: quarto,
        MAP: json.dumps(page_manifest, indent=2, sort_keys=True) + "\n",
        NAVIGATION: json.dumps(
            {"schemaVersion": 1, "items": adjacent}, indent=2, sort_keys=True
        )
        + "\n",
        PREREQUISITES: json.dumps(prerequisites, indent=2, sort_keys=True) + "\n",
        CARDS: "\n".join(cards) + "\n",
    }
    for course in catalog["courses"]:
        course_root = ROOT / "docs" / "courses" / course["id"]
        outputs[course_root / "_outcomes.yml"] = (
            json.dumps(
                {"course_id": course["id"], "outcomes": course["outcomes"]},
                indent=2,
                ensure_ascii=False,
            )
            + "\n"
        )
        for unit in course["units"]:
            outputs[ROOT / "docs" / unit["directory"] / "_metadata.yml"] = (
                json.dumps(
                    {
                        "id": unit["id"],
                        "title": unit["title"],
                        "course_id": course["id"],
                        "outcomes": unit["outcomes"],
                    },
                    indent=2,
                    ensure_ascii=False,
                )
                + "\n"
            )
    return outputs


def yaml_scalar(value: object) -> str:
    return json.dumps(str(value))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if generated files are stale"
    )
    args = parser.parse_args()
    issues = validate_catalog(CATALOG, docs_root=ROOT / "docs")
    if issues:
        print("\n".join(str(issue) for issue in issues), file=sys.stderr)
        return 1
    catalog = load_structured_data(CATALOG)
    stale: list[Path] = []
    for path, expected in generated_files(catalog).items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if stale:
        print("Generated curriculum files are stale:", file=sys.stderr)
        print("\n".join(f"- {path}" for path in stale), file=sys.stderr)
        print("Run: python scripts/generate_navigation.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
