"""Shared building blocks used by math branch packages."""

from edumath.core.answers import (
    AnswerCheck,
    NumericTolerance,
    check_expression_answer,
    check_numeric_answer,
)
from edumath.core.exercises import (
    AnswerType,
    Difficulty,
    Exercise,
    render_exercise_markdown,
    render_practice_set,
)
from edumath.core.expressions import (
    MathExpression,
    expression_equivalent,
    infer_variable,
    parse_equation,
    parse_expression,
)
from edumath.core.lessons import LearningObjective, Lesson, LessonSection, StudyPath
from edumath.core.plots import (
    ExplicitFunction2D,
    ParametricCurve2D,
    PlotRange,
    PlotScene2D,
    PlotStyle,
    Point2D,
    PolarCurve2D,
    SampledCurve2D,
    Segment2D,
    Viewport2D,
)
from edumath.core.quizzes import (
    AnswerOption,
    Question,
    QuestionAnswerType,
    QuestionValidator,
    QuizResult,
    QuizSession,
    SympyResolver,
    SympyResolverName,
)
from edumath.core.solutions import (
    ExerciseSolution,
    SolutionReveal,
    SolutionStep,
    WorkedSolution,
    render_solution_callout,
    render_solution_details,
)
from edumath.core.widgets import NotebookDisplay

__all__ = [
    "AnswerCheck",
    "AnswerOption",
    "AnswerType",
    "Difficulty",
    "Exercise",
    "ExerciseSolution",
    "ExplicitFunction2D",
    "LearningObjective",
    "Lesson",
    "LessonSection",
    "MathExpression",
    "NotebookDisplay",
    "NumericTolerance",
    "ParametricCurve2D",
    "PlotRange",
    "PlotScene2D",
    "PlotStyle",
    "Point2D",
    "PolarCurve2D",
    "Question",
    "QuestionAnswerType",
    "QuestionValidator",
    "QuizResult",
    "QuizSession",
    "SampledCurve2D",
    "Segment2D",
    "SolutionReveal",
    "SolutionStep",
    "StudyPath",
    "SympyResolver",
    "SympyResolverName",
    "Viewport2D",
    "WorkedSolution",
    "check_expression_answer",
    "check_numeric_answer",
    "expression_equivalent",
    "infer_variable",
    "parse_equation",
    "parse_expression",
    "render_exercise_markdown",
    "render_practice_set",
    "render_solution_callout",
    "render_solution_details",
]
