name: Documentation

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

env:
  VIRTUALENV_ACTIVATORS: "bash,python"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: edumath
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.10"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --extras "dev"

      - name: Render Quarto site
        run: makim docs.build

      - name: GitHub Pages action
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
